version: 1.0.{build}

image: Visual Studio 2017

build:
  verbosity: detailed

cache:
- '%USERPROFILE%\.nuget\packages -> paket.lock'

build_script:
- cmd: dotnet build -c Release src

test_script:
- cmd: dotnet test -c Release src\FSharp.JsonSkippable.Tests

artifacts:
- path: '**\Release\*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: gABwq0g1pWrk4CtgW6YmilPC7emawNAbeC/c3+jn9TMEMiljc2UR/MlI9r89yKlS
  on:
    appveyor_repo_tag: true
